/**
 * PDF Export — opens a styled print-ready window for "Save as PDF".
 * No external dependencies needed.
 */

import type { SessionReport } from "./groqExplainer";
import type { Session } from "@/types/api";

const pct = (v: number | null | undefined) =>
  v != null ? (v * 100).toFixed(1) + "%" : "—";

export function downloadReportAsPDF(
  report: SessionReport,
  sessions: Session[],
): void {
  const html = buildHTML(report, sessions);
  const win = window.open("", "_blank");
  if (!win) {
    alert("Please allow popups to download the PDF report.");
    return;
  }
  win.document.write(html);
  win.document.close();
  // Give time for styles to render
  setTimeout(() => win.print(), 400);
}

function buildHTML(report: SessionReport, sessions: Session[]): string {
  const ts = new Date(report.generatedAt).toLocaleString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });

  const sessionRows = sessions
    .map(
      (s) => `
    <tr>
      <td>${s.task_type}</td>
      <td>${new Date(s.started_at).toLocaleTimeString()}</td>
      <td>${s.duration_minutes ?? "—"} min</td>
      <td>${pct(s.avg_instability)}</td>
      <td>${pct(s.avg_drift)}</td>
      <td>${pct(s.avg_fatigue)}</td>
      <td>${pct(s.deep_work_ratio)}</td>
      <td>${s.switch_count ?? 0}</td>
    </tr>`,
    )
    .join("");

  const recs = report.recommendations
    .map((r) => `<li>${r}</li>`)
    .join("");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <title>CortexFlow — ${report.title}</title>
  <style>
    * { margin:0; padding:0; box-sizing:border-box }
    body { font-family: 'Segoe UI', -apple-system, sans-serif; color:#1a1a2e; padding:40px; max-width:900px; margin:0 auto; line-height:1.6 }
    h1 { font-size:24px; color:#6c63ff; margin-bottom:4px }
    .subtitle { font-size:12px; color:#888; margin-bottom:32px }
    h2 { font-size:16px; color:#6c63ff; margin-top:28px; margin-bottom:8px; border-bottom:2px solid #6c63ff33; padding-bottom:4px }
    p { font-size:14px; margin-bottom:12px }
    .overview-box { background:#f4f3ff; border-left:4px solid #6c63ff; padding:16px; border-radius:4px; margin-bottom:24px }
    table { width:100%; border-collapse:collapse; font-size:12px; margin-top:8px }
    th { background:#6c63ff; color:#fff; text-align:left; padding:8px 10px; font-weight:500 }
    td { padding:6px 10px; border-bottom:1px solid #e0e0e0 }
    tr:nth-child(even) { background:#fafafa }
    .section { margin-bottom:20px }
    .section p { margin-bottom:8px }
    ul { margin-left:20px; margin-top:4px }
    li { font-size:14px; margin-bottom:6px }
    .footer { margin-top:40px; text-align:center; font-size:11px; color:#999; border-top:1px solid #e0e0e0; padding-top:12px }
    @media print { body { padding:20px } }
  </style>
</head>
<body>
  <h1>🧠 ${report.title}</h1>
  <div class="subtitle">Generated ${ts} — CortexFlow Neurological Assessment</div>

  <div class="overview-box">
    <p><strong>Overview:</strong> ${report.overview}</p>
  </div>

  <h2>Session Data (Last 10 Minutes)</h2>
  <table>
    <thead>
      <tr>
        <th>Task</th>
        <th>Started</th>
        <th>Duration</th>
        <th>Instability</th>
        <th>Drift</th>
        <th>Fatigue</th>
        <th>Deep Work</th>
        <th>Switches</th>
      </tr>
    </thead>
    <tbody>${sessionRows}</tbody>
  </table>

  <h2>Instability Analysis (Salience Network)</h2>
  <div class="section"><p>${report.instabilityAnalysis}</p></div>

  <h2>Drift Analysis (Default Mode Network)</h2>
  <div class="section"><p>${report.driftAnalysis}</p></div>

  <h2>Fatigue Analysis (Executive Control Network)</h2>
  <div class="section"><p>${report.fatigueAnalysis}</p></div>

  <h2>Deep Work Quality</h2>
  <div class="section"><p>${report.deepWorkAnalysis}</p></div>

  <h2>Recommendations</h2>
  <ul>${recs}</ul>

  <div class="footer">
    CortexFlow — AI-Powered Cognitive Performance Monitor<br/>
    This report is generated by Groq LLM analysis and is for informational purposes only.
  </div>
</body>
</html>`;
}
