# Generated by Django 4.2.28 on 2026-02-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='deep_work_windows',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='total_windows',
            field=models.IntegerField(default=0),
        ),
    ]
